"use client";

import { ReactNode } from "react";
import { Card, CardBody, CardHeader } from "@/components/ui/Card";
import { useLanguage } from "@/lib/i18n/language";

export default function TermsPage(): ReactNode {
  const { language } = useLanguage();

  return (
    <div style={{ maxWidth: "800px", margin: "3rem auto", padding: "0 1.5rem" }}>
      <Card>
        <CardHeader>
          <h1 style={{ fontSize: "1.75rem" }}>
            {language === "ko" ? "이용약관" : "Terms of Service"}
          </h1>
        </CardHeader>
        <CardBody style={{ lineHeight: "1.7", display: "flex", flexDirection: "column", gap: "1rem" }}>
          <p>{language === "ko" ? "최근 수정일: 2026년 7월 15일" : "Last updated: July 15, 2026"}</p>
          {language === "ko" ? (
            <>
              <p>
                Frontend Toolbox에 접속하고 서비스를 이용함으로써 귀하는 다음 이용약관을 준수하고 이에 구속되는 것에 동의하게 됩니다.
              </p>
              <h3 style={{ fontSize: "1.1rem", marginTop: "1rem" }}>1. 허용되는 사용 범위</h3>
              <p>
                귀하는 별도의 크레딧 표기(출처 표시) 없이도 개인 및 상업용 소프트웨어 프로젝트 모두에서 생성된 TypeScript 인터페이스, 모의 데이터 구조 및 CSS 그림자 속성을 자유롭게 사용할 수 있습니다.
              </p>
              <h3 style={{ fontSize: "1.1rem", marginTop: "1rem" }}>2. 보증의 부인</h3>
              <p>
                Frontend Toolbox는 모든 스크립트와 도구를 &quot;있는 그대로&quot; 제공하며 어떤 종류의 명시적이거나 묵시적인 보증도 하지 않습니다. 당사는 코드 변환 유틸리티가 특이 케이스 입력에 대해 100% 컴파일 오류가 발생하지 않을 것임을 보장하지 않습니다. 생성된 결과물은 검토 후 안전하게 사용하시기 바랍니다.
              </p>
            </>
          ) : (
            <>
              <p>
                By accessing and utilizing Frontend Toolbox, you agree to comply with and be bound by the following terms of service.
              </p>
              <h3 style={{ fontSize: "1.1rem", marginTop: "1rem" }}>1. Permitted Use</h3>
              <p>
                You are free to use all generated TypeScript interfaces, mock structures, and CSS shadow properties for both personal and commercial software projects without attribution.
              </p>
              <h3 style={{ fontSize: "1.1rem", marginTop: "1rem" }}>2. Disclaimer of Warranties</h3>
              <p>
                Frontend Toolbox provides all scripts and tools on an &quot;as is&quot; and &quot;as available&quot; basis. We make no warranty that our code translation utility will be 100% free of compile errors for all edge-case payloads. Use code generated by this platform responsibly and test outputs before deploying to production environments.
              </p>
            </>
          )}
        </CardBody>
      </Card>
    </div>
  );
}
